[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 13.0

[colors.primary]
background = "#0f1117"  # black background
foreground = "#FFFFFF"  # white text

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.normal]
black = "#000000"
red = "#AA0000"
green = "#00AA00"
yellow = "#AA5500"
blue = "#00AAAA"
magenta = "#AA00AA"
cyan = "#00AAAA"
white = "#AAAAAA"

[colors.bright]
black = "#555555"
red = "#FF5555"
green = "#55FF55"
yellow = "#FFFF55"
blue = "#55FFFF"
magenta = "#FF55FF"
cyan = "#55FFFF"
white = "#FFFFFF"

[terminal.shell]
program = "/run/current-system/sw/bin/zsh"
args = ["-l"]

